Changes in present layer
DrDLivsey/SimpleUnsplashClient pull request #3
Opened 2023-08-11 07:22 UTC by DrDLivsey

2023-08-11 07:52 UTC, trszdev commented
По проекту:
1. В MainStoryBoard надо убрать неиспользуемые вьюконтроллеры:

<img width="372" alt="изображение" src="https://github.com/DrDLivsey/SimpleUnsplashClient/assets/9008471/f4a5fc8e-e630-4431-83a6-5e39cb45c189">

2. Папки с модулями я бы переименовал: ImageItemCSModule -> ImageDetailModule, ImageListCSModule -> ImageCollectionModule
3. Папки проекта называются с большой буквы поэтому я бы переименовал localDataSource, remoteDataSource

2023-08-11 08:47 UTC, trszdev requested changes

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +//    override func viewWillAppear(_ animated: Bool) {
Это уже не нужно

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +    private let imageListRepository: ImagesRepositoryProtocol
imageListRepository -> imagesRepository

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +        //        loadImages()
не нужно больше

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionPresenter.swift
> +                    string: "\(metadata.description)",
Просто metadata.description, без дополнительного оборачивания

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +// класс для отображения
Настолько очевидные комменты лучше не писать, разработчики итак это поймут

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +    // метод конфигурирования ячейки для списка
Очевидный коммент (2)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    // настройка отображения UICollection
Очевидный коммент (3)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +        let layout = UICollectionViewFlowLayout()
Можно сделать такой extension:

```
extension UICollectionViewFlowLayout {
   static func makeImageCollectionLayout() -> UICollectionViewFlowLayout {
   
        layout.scrollDirection = .vertical
        layout.itemSize = CGSize(width: 150, height: 150)
        collectionView.contentInsetAdjustmentBehavior = .always

        layout.sectionInsetReference = .fromSafeArea
        layout.sectionInset.top = 0
        layout.sectionInset.bottom = 0
        layout.sectionInset.left = 30
        layout.sectionInset.right = 30


        layout.minimumLineSpacing = 10
        layout.minimumInteritemSpacing = 10
        return layout
   }
}
```

и потом в конструкторе ImageCollectionVC его использовать

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionViewState.swift
> +
Добавь плиз правило в линтер чтобы подряд идущих пустых строк больше 1 не было

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +final class ImageListRepository: ImagesRepositoryProtocol {
ImagesRepository+ название файла

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    func getImageItem(imgID: String, completion: @escaping(Result<ImageMetadata, ImageListRepository.ImageListRepositoryError>) -> Void)
Добавь плиз правило в swiftlint на ограничение по длине строки 120 символов

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    // доступная для работы извне переменная-дубль _imagesInternalModel
Очевидный коммент (4)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    // итоговое хранилище всех моделей для отображения
Очевидный коммент (5)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +        // проверяем есть ли кэшированные данные
Очевидный коммент (6)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +            // если кэша нет, то дергаем ручку
Очевидный коммент (7)

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +                    completion(.failure(self.convertImageListRemoteDataSourceErrorToImageListRepositoryError(
convertImageListRemoteDataSourceErrorToImageListRepositoryError - уффф сильное название, очень желательно выбирать названия как можно лаконичнее и проще

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +                    completion(.failure(self.convertImageListRemoteDataSourceErrorToImageListRepositoryError(
Я бы сделал экстеншн для error: var imagesRepositoryError: Error

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        // добавляем в него созданные элементы
Лучше вынести в отдельный методы настройку (1) label, (2) stackView, (3) view+constraints; комментарии очевидные, лучше убрать

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    var spinner = Spinner()
Мне кажется что spinner и alert должны быть приватными

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +    let spinner = UIActivityIndicatorView(style: .large)
spinner/label - сделать приватными; если нужно текст лейбла менять извне, добавь метод func update(text: String) {}

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/StartScreen.swift
> +    @IBOutlet weak var screenTitle: UILabel?
@IBOutlet/@IBAction сделать приватными

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/StartScreen.swift
> +    private var imageCollectionBuilder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
Не зачем хранить, можно в openImageList() сразу создавать

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +                // MARK: СДЕЛАТЬ ОТОБРАЖЕНИЕ ДВУХ РАЗНЫХ ЭКРАНОВ, ОДИН С ВОЗМОЖНОСТЬЮ ОБНОВИТЬ ДАННЫЕ, ДРУГОЙ - БЕЗ
Я бы перенес коммент в кейс .noRetryError:

// TODO: implement no retry error

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    private var builder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
не используется

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +            withReuseIdentifier: "ImageCollectionCell",
"ImageCollectionCell" в константу

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +protocol ImageDetailVCInput: AnyObject {
Тут и в другом модуле неправильно протокол назван\
ImageDetailVCInput -> ImageDetailViewInput, презентер не должен знать что за вью у него лежит

2023-08-11 08:47 UTC, trszdev commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +        navigationItem.title = imageModel.imageUser
NIT: это поле я бы выставлял в роутере, перед презентом, потому что сейчас у тебя тайтл в шапке моргает

2023-08-11 08:58 UTC, trszdev commented
еще момент:

в ImagesRepository.getImageItems(currentPage: Int) completion вызывается внутри accessQueue, так лучше не делать, потому что остальные потоки могут долго дожидаться accessQueue. Часто встречается такой паттерн для синхронизации переменных:

```swift
var imagesInternalModel: [ImageMetadata] {
    get {
      accessQueue.sync { _imagesInternalModel  }
    }
    set {
      // Если очередь serial:
      // accessQueue.async { [weak self] in self?._imagesInternalModel = newValue }
     // Если очередь concurrent:
      accessQueue.async(flags: .barrier) { [weak self] in self?._imagesInternalModel = newValue }
    }
}
```

и дальше ты везде и снаружи и внутри просто обращаешься к imagesInternalModel

кстати в getImageItem(imgID: String) ты про это забыл и там возможна гонка

2023-08-11 09:04 UTC, trszdev requested changes

2023-08-11 09:04 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +            output = ImageCollectionInteractorError.retryError
тут можно просто return .retryError

2023-08-11 09:04 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +            output = ImageCollectionInteractorError.noRetryError
тут можно просто return .noRetryError

2023-08-11 09:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +//    override func viewWillAppear(_ animated: Bool) {
1. Неиспользоуемые view controller'ы удалены
2. Папки переименовал в ImageDetailModule, ImageCollectionModule
3. Папки переименовал в LocalDataSource, RemoteDataSource

Закомменченный метод viewwillload удалил

2023-08-11 09:53 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +    private let imageListRepository: ImagesRepositoryProtocol
Переименовал по всему проекту
imageList... -> images...

2023-08-11 09:53 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +        //        loadImages()
Убрал

2023-08-11 09:54 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionPresenter.swift
> +                    string: "\(metadata.description)",
Исправлено

2023-08-11 09:55 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +// класс для отображения
Убрал.

2023-08-11 09:56 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +    // метод конфигурирования ячейки для списка
Убрал

2023-08-11 09:56 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    // настройка отображения UICollection
Убрал

2023-08-11 10:08 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionViewState.swift
> +
Добавил, поправил все, что было найдено

2023-08-11 10:09 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +final class ImageListRepository: ImagesRepositoryProtocol {
поправил

2023-08-11 10:33 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    func getImageItem(imgID: String, completion: @escaping(Result<ImageMetadata, ImageListRepository.ImageListRepositoryError>) -> Void)
Оно стояло, но было исключение для объявления функций. Поменял эту настройку, поправил все, что было найдено

2023-08-11 10:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    // доступная для работы извне переменная-дубль _imagesInternalModel
Убрал

2023-08-11 10:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +    // итоговое хранилище всех моделей для отображения
Убрал

2023-08-11 10:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +        // проверяем есть ли кэшированные данные
Убрал

2023-08-11 10:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +            // если кэша нет, то дергаем ручку
Убрал

2023-08-11 10:42 UTC, DrDLivsey commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        // добавляем в него созданные элементы
Комменты убрал. На методы разбил

2023-08-11 10:44 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    var spinner = Spinner()
В классе Spinner сделал свойства spinner, label приватными. А что ты подразумеываешь под alert?

2023-08-11 10:45 UTC, DrDLivsey commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +    let spinner = UIActivityIndicatorView(style: .large)
Сделал

2023-08-11 10:49 UTC, DrDLivsey commented on SimpleUnsplashClientNew/StartScreen.swift
> +    @IBOutlet weak var screenTitle: UILabel?
Сделано

2023-08-11 10:52 UTC, DrDLivsey commented on SimpleUnsplashClientNew/StartScreen.swift
> +    private var imageCollectionBuilder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
Перенес imageCollectionBuilder в метод openImageList(), сделал let

2023-08-11 10:53 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/ImageCollectionInteractor.swift
> +                // MARK: СДЕЛАТЬ ОТОБРАЖЕНИЕ ДВУХ РАЗНЫХ ЭКРАНОВ, ОДИН С ВОЗМОЖНОСТЬЮ ОБНОВИТЬ ДАННЫЕ, ДРУГОЙ - БЕЗ
Перенес

2023-08-11 11:20 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +    private var builder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
Убрал

2023-08-11 11:32 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +            withReuseIdentifier: "ImageCollectionCell",
Не понял, она же и так константа

2023-08-11 11:34 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +protocol ImageDetailVCInput: AnyObject {
Переименовал:
ImageDetailVCInput в ImageDetailViewInput,
ImageCollectionVCInput в ImageCollectionViewInput

2023-08-11 11:40 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +        navigationItem.title = imageModel.imageUser
У меня нет роутера для этого модуля. А до этого только у builder есть работа с UI

2023-08-11 11:42 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +            output = ImageCollectionInteractorError.retryError
Исправил

2023-08-11 11:42 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +            output = ImageCollectionInteractorError.noRetryError
Исправил

2023-08-11 11:46 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +        let layout = UICollectionViewFlowLayout()
Если так сделать xcode ругается на collectionView.contentInsetAdjustmentBehavior = .always - **instance member 'collectionView' cannot be used on type 'UICollectionViewFlowLayout'**

2023-08-11 13:32 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +        let layout = UICollectionViewFlowLayout()
Поправил.

2023-08-11 13:49 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImageListRepository.swift
> +                    completion(.failure(self.convertImageListRemoteDataSourceErrorToImageListRepositoryError(
Переделал в extension

2023-08-11 13:51 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageListCSModule/View/ImageCollectionVC.swift
> +            withReuseIdentifier: "ImageCollectionCell",
Вынес "ImageCollectionCell" в тело класса как константу cellName

2023-08-11 14:04 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageItemCSModule/View/ImageDetailVC.swift
> +        navigationItem.title = imageModel.imageUser
Сделано

2023-08-11 14:20 UTC, trszdev requested changes

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +    private func convertImagesRepositoryErrorToImageCollectionInteractorError(
Это больше не нужно

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    init(intercator: ImageCollectionInteractorInput) {
interactor - опечатка

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var cellName = "ImageCollectionCell"
var -> let

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            // Если очередь serial:
Коммент лишний)

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        func configureLabel() {
1) Методы внутри методов стараемся не делать
2) А кто вызывает configureLabel(), configureStack(), configureView() ?

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            completion(.failure(ImagesRepositoryError.internalError))
completion(.failure(.internalError))

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            return ImagesRepository.ImagesRepositoryError.internalError
return .internalError

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            return ImagesRepository.ImagesRepositoryError.requestError
return .requestError

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +    static var sharedInstance = ImagesRepository()
static let sharedInstance

2023-08-11 14:20 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +    @IBOutlet weak var imageThumb: UIImageView?
@IBOutlet private

2023-08-11 14:59 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionCell/ImageCollectionCell.swift
> +    @IBOutlet weak var imageThumb: UIImageView?
Поправил

2023-08-11 14:59 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +    static var sharedInstance = ImagesRepository()
Поправил

2023-08-11 15:00 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            return ImagesRepository.ImagesRepositoryError.requestError
Поправил

2023-08-11 15:01 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            completion(.failure(ImagesRepositoryError.internalError))
Поправил

2023-08-11 15:01 UTC, DrDLivsey commented on SimpleUnsplashClientNew/Logic/Service/ImagesRepository.swift
> +            // Если очередь serial:
Убрал

2023-08-11 15:01 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var cellName = "ImageCollectionCell"
Поправил

2023-08-11 15:02 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    init(intercator: ImageCollectionInteractorInput) {
Поправил

2023-08-11 15:03 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/ImageCollectionInteractor.swift
> +    private func convertImagesRepositoryErrorToImageCollectionInteractorError(
Убрал

2023-08-11 15:07 UTC, DrDLivsey commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        func configureLabel() {
Никто) Поправил

2023-08-14 07:21 UTC, trszdev requested changes

2023-08-14 07:21 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    var spinner = Spinner()
private let

2023-08-14 07:21 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var interactor: ImageCollectionInteractorInput
private let

2023-08-14 07:21 UTC, trszdev commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var builder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
не используется, надо убрать

2023-08-14 07:21 UTC, trszdev commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        configureLabel()
У тебя этот метод при каждом вызове loading будет. То есть в стек будет добавляться лейбл, стек на вью итд. Такой код размещают во viewDidLoad/в конструкторе UIView

2023-08-14 07:21 UTC, trszdev commented on SimpleUnsplashClientNew/StartScreen.swift
> +    override func viewDidLoad() {
Можно не оверрайдить раз ничего не меняется

2023-08-14 07:25 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    var spinner = Spinner()
Поправил

2023-08-14 07:27 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var interactor: ImageCollectionInteractorInput
Поправил

2023-08-14 07:31 UTC, DrDLivsey commented on SimpleUnsplashClientNew/ImageCollectionModule/View/ImageCollectionVC.swift
> +    private var builder: ImageCollectionBuilderProtocol = ImageCollectionBuilder()
Убрал

2023-08-14 07:32 UTC, DrDLivsey commented on SimpleUnsplashClientNew/StartScreen.swift
> +    override func viewDidLoad() {
Убрал

2023-08-14 07:57 UTC, DrDLivsey commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        configureLabel()
Тут не понял. У UIView же нет viewdidload. Что такое конструктор UIView?

2023-08-14 08:14 UTC, DrDLivsey commented on SimpleUnsplashClientNew/SharedViews/Spinner.swift
> +        configureLabel()
Перенес в init()

2023-08-14 08:16 UTC, trszdev approved these changes

2023-08-14 08:19 UTC, merged